#pragma once

#include "all_any.hh"
#include "append.hh"
#include "concat.hh"
#include "filter.hh"
#include "foldl.hh"
#include "foldr.hh"
#include "head.hh"
#include "is_empty.hh"
#include "length.hh"
#include "map.hh"
#include "nth.hh"
#include "prepend.hh"
#include "reverse.hh"
#include "set.hh"
#include "tail.hh"
#include "take_drop.hh"
