#pragma once

#include "add.hh"
#include "dec.hh"
#include "div.hh"
#include "eq.hh"
#include "ge.hh"
#include "gt.hh"
#include "inc.hh"
#include "le.hh"
#include "lshift.hh"
#include "lt.hh"
#include "mod.hh"
#include "rshift.hh"
#include "sub.hh"
