#pragma once

#include "add.hh"
#include "dec.hh"
#include "div.hh"
#include "eq.hh"
#include "ge.hh"
#include "gt.hh"
#include "incr.hh"
#include "le.hh"
#include "left_shift.hh"
#include "lt.hh"
#include "mod.hh"
#include "mul.hh"
#include "sub.hh"
